version: '3'
services:
  web:
    image: webapp:v1
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`react.turkiyeoku.com`)"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.routers.web.tls.certresolver=http"

networks:
  proxy:
    external: true